services:
  postgres:
    image: postgres:17-alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 17001:8080
    depends_on:
      - postgres
